#!/usr/bin/env python3
"""Materialize the echo-stub Slurm commands into an episode sandbox.

    uv run --with pyyaml src/hpcbench/stubs/install_stubs.py <sandbox-dir>

Creates this, and prints the environment the episode should run under:

    <sandbox>/work/                the agent's working directory (job.sh, prompt.md, assets)
    <sandbox>/runtime/bin/         the shims, first on PATH
    <sandbox>/runtime/slurm_stub.py
    <sandbox>/runtime/cluster.json what the stubs are allowed to know
    <sandbox>/runtime/state.json   the job table
    <sandbox>/runtime/calls.jsonl  the call log

`runtime/` sits outside `work/` deliberately. If the job table and the call log lived in the
agent's own directory, an agent could read the log it is being judged by, and every filesystem
case would have a spurious way to "pass" by editing evidence.

**`cluster.json` is a reduction of `center.yaml`, not a copy.** The shims are on the agent's
PATH, so anything they can read the agent can read too. It therefore carries only facts a real
cluster reveals through its own interfaces — the partition table `sinfo` prints, the module list
`module avail` prints, the quota `quota` prints. The guardrails and the prose stay out, because
those are the content of the `INSTRUCTIONS.md` whose absence defines the doc-absent arm. Copying
the descriptor wholesale would hand every doc-absent episode the document through the back door
and silently destroy the contrast the benchmark exists to measure.

This is the only part of the stub layer that needs PyYAML. The stub itself is stdlib-only and
reads the JSON this produces.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import stat
import sys
from pathlib import Path

import yaml

if __package__ in (None, ""):  # invoked as a script rather than imported
    # ...and the target is `src/`, not the repo root. The repo root holds no `hpcbench`,
    # so getting this index wrong makes the next line raise — invisibly, because `uv run`
    # leaves an editable install whose .pth already puts `src` on the path.
    sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from hpcbench.paths import CENTER  # noqa: E402

# `slurm_stub.py` sits beside this file and is copied into each sandbox, so it stays found
# by directory, not by descriptor path. It imports nothing outside the standard library.
HERE = Path(__file__).resolve().parent

# Every command the shim layer answers for. Slurm commands no case exercises are still shimmed:
# an unshimmed `sacctmgr` on a login node would reach the real one.
SHIMMED = (
    "sbatch", "squeue", "sacct", "sacctmgr", "scancel", "scontrol", "sinfo", "srun", "salloc",
    "sattach", "sprio", "sshare", "sreport", "module", "quota", "mkdir", "sstat",
)

WRAPPER = """#!/bin/sh
# Echo-stub for `{command}`. Logs the call, answers as the declared cluster would, executes
# nothing. Generated by src/hpcbench/stubs/install_stubs.py — edit that, not this.
HPCBENCH_RUNTIME='{runtime}' exec '{python}' '{stub}' {command} "$@"
"""


def reduce_descriptor(center: dict) -> dict:
    """center.yaml -> the subset the stubs may know. See the module docstring on why."""
    account = center["account"]
    filesystems = {}
    for name, declared in center["filesystems"].items():
        usage = center["stub"]["usage"].get(name, {})
        limit = (
            f"{declared['quota_tb']}T" if "quota_tb" in declared
            else f"{declared['quota_gb']}G"
        )
        filesystems[name] = {
            "path": declared["path"].replace("$USER", account["user"]),
            "limit": limit,
            "used": str(usage.get("used", 0)),
            "inode_limit": str(declared.get("inode_quota", "")),
            "used_inodes": str(usage.get("used_inodes", 0)),
        }

    nodes = {}
    for name, declared in center["nodes"].items():
        nodes[name] = {
            "count": declared["count"],
            "cpus": declared["cores"],
            "memory_gb": declared["memory_gb"],
            "gpus_per_node": declared.get("gpus_per_node", 0),
            "nodelist": declared["hostname_pattern"],
            "hostname_example": declared["hostname_example"],
        }

    return {
        "center": {
            "name": center["center"]["name"],
            "short_name": center["center"]["short_name"],
        },
        "account": account["name"],
        "user": account["user"],
        "uid": account["uid"],
        "login_host": center["nodes"]["login"]["hostname_example"],
        "scheduler_version": center["scheduler"]["version"],
        "partitions": [
            {
                "name": partition["name"],
                "node_class": partition["node_class"],
                "max_nodes": partition["max_nodes"],
                "max_time": partition["max_time"],
                "gpus": partition["gpus"],
                "default": bool(partition.get("default")),
            }
            for partition in center["partitions"]
        ],
        "nodes": nodes,
        "filesystems": filesystems,
        "modules": list(center["modules"]),
        "timing": {
            "pending_seconds": center["stub"]["pending_seconds"],
            "short_job_seconds": center["stub"]["short_job_seconds"],
            "long_job_threshold": center["stub"]["long_job_threshold"],
        },
    }


def durable_interpreter() -> str:
    """An interpreter that will still exist after this process exits.

    `sys.executable` is the wrong answer here. Run under `uv run --with pyyaml`, it points into
    an ephemeral build venv that uv deletes when the command finishes — so shims baked with it
    work during installation and fail afterwards, which is precisely the failure a harness
    would misread as the agent doing something wrong. `sys.base_prefix` is the real interpreter
    the venv was built from and outlives it. The stub imports nothing outside the standard
    library, so any python3 will do.
    """
    candidate = Path(sys.base_prefix) / "bin" / "python3"
    return str(candidate) if candidate.exists() else sys.executable


def install(
    sandbox: Path,
    center_path: Path = CENTER,
    python: str | None = None,
    verify: bool = True,
) -> dict:
    """Build the sandbox. Returns the environment an episode should run under."""
    center = yaml.safe_load(center_path.read_text())
    runtime = sandbox / "runtime"
    work = sandbox / "work"
    binaries = runtime / "bin"
    binaries.mkdir(parents=True, exist_ok=True)
    work.mkdir(parents=True, exist_ok=True)

    # A copy, not a symlink: an episode has to stay replayable after the checkout moves or the
    # working tree changes underneath it.
    stub = runtime / "slurm_stub.py"
    shutil.copy2(HERE / "slurm_stub.py", stub)

    (runtime / "cluster.json").write_text(
        json.dumps(reduce_descriptor(center), indent=1, sort_keys=True) + "\n"
    )
    (runtime / "state.json").write_text(json.dumps({"next_job_id": 1000, "jobs": {}}) + "\n")
    (runtime / "calls.jsonl").write_text("")

    interpreter = python or durable_interpreter()
    for command in SHIMMED:
        target = binaries / command
        target.write_text(
            WRAPPER.format(
                command=command, runtime=runtime, python=interpreter, stub=stub
            )
        )
        target.chmod(target.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    environment = {
        "PATH": f"{binaries}{os.pathsep}{os.environ.get('PATH', '')}",
        "HPCBENCH_RUNTIME": str(runtime),
        # `USER` is deliberately NOT exported, though cluster.json carries the fictional name and
        # the stubs answer with it.
        #
        # It was, for two episodes: so that `/scratch/$USER` in the case scripts expanded the same
        # way on every machine, and so the operator's real account name stayed out of committed
        # results. Both are cosmetic, and overriding `USER` breaks credential resolution for the
        # agent under test — the first live run died with "Invalid API key" and scored as an
        # ordinary failed episode. Path tidiness is not worth an environment the agent cannot
        # authenticate in.
        #
        # Consequence to know: `$USER` in a transcript is the real account running the harness. If
        # results are published, that name goes with them.
    }

    if verify:
        # Exercise one shim end to end. A sandbox whose shims do not run is indistinguishable,
        # from the outside, from an agent that never called sbatch — so fail here, loudly, and
        # not in the results. The installer is allowed to execute things; the stub is not.
        import subprocess

        probe = subprocess.run(
            [str(binaries / "sinfo"), "--noheader"],
            capture_output=True, text=True, env={**os.environ, **environment},
        )
        if probe.returncode != 0 or "standard" not in probe.stdout:
            raise RuntimeError(
                f"shim self-check failed (exit {probe.returncode}). "
                f"stdout={probe.stdout!r} stderr={probe.stderr!r}"
            )
        # Leave no trace of the self-check in the evidence.
        (runtime / "calls.jsonl").write_text("")

    return environment


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("sandbox", type=Path, help="directory to create the sandbox in")
    parser.add_argument("--center", type=Path, default=CENTER, help="path to center.yaml")
    parser.add_argument("--episode", default="", help="episode id, recorded in the call log")
    arguments = parser.parse_args()

    environment = install(arguments.sandbox.resolve(), arguments.center)
    if arguments.episode:
        environment["HPCBENCH_EPISODE"] = arguments.episode

    print(f"# sandbox ready: {arguments.sandbox.resolve()}", file=sys.stderr)
    print(f"# {len(SHIMMED)} shims installed; nothing they answer reaches a scheduler",
          file=sys.stderr)
    for key, value in environment.items():
        print(f"export {key}='{value}'")
    return 0


if __name__ == "__main__":
    sys.exit(main())
