# Accelerator resources managed by Slurm.

NodeName=scc-g001 AutoDetect=off Name=gpu File=/dev/null Flags=CountOnly
NodeName=scc-g001 AutoDetect=off Name=gpu File=/dev/zero Flags=CountOnly
NodeName=scc-g001 AutoDetect=off Name=gpu File=/dev/full Flags=CountOnly
NodeName=scc-g001 AutoDetect=off Name=gpu File=/dev/random Flags=CountOnly
