# Accelerator resources managed by Slurm.

NodeName=c3 AutoDetect=off Name=gpu File=/dev/null Flags=CountOnly
NodeName=c3 AutoDetect=off Name=gpu File=/dev/zero Flags=CountOnly
NodeName=c3 AutoDetect=off Name=gpu File=/dev/full Flags=CountOnly
NodeName=c3 AutoDetect=off Name=gpu File=/dev/random Flags=CountOnly
