ClusterName=scc
SlurmctldHost=slurmctld

SlurmUser=slurm
SlurmctldPort=6817
SlurmdPort=6818
AuthType=auth/munge

StateSaveLocation=/var/lib/slurm
SlurmdSpoolDir=/var/lib/slurmd
SwitchType=switch/none
MpiDefault=none
SlurmctldPidFile=/var/run/slurmctld/slurmctld.pid
SlurmdPidFile=/var/run/slurmd/slurmd.pid
ProctrackType=proctrack/cgroup
ReturnToService=2
TaskPlugin=task/cgroup
SlurmdParameters=config_overrides
MailProg=/bin/true

SlurmctldTimeout=300
SlurmdTimeout=300
InactiveLimit=0
MinJobAge=300
KillWait=30
Waittime=0

SchedulerType=sched/backfill
EnforcePartLimits=YES
SelectType=select/cons_tres
SelectTypeParameters=CR_CPU_Memory

SlurmctldDebug=info
SlurmctldLogFile=/var/log/slurm/slurmctld.log
SlurmdDebug=info
SlurmdLogFile=/var/log/slurm/slurmd-%n.log
JobCompType=jobcomp/filetxt
JobCompLoc=/var/log/slurm/jobcomp.log

JobAcctGatherType=jobacct_gather/linux
JobAcctGatherFrequency=5
AccountingStorageType=accounting_storage/slurmdbd
AccountingStorageHost=slurmdbd
AccountingStoragePort=6819
AccountingStorageEnforce=associations
