# SCC Slurm configuration.

ClusterName=scc
SlurmctldHost=slurmctld

SlurmUser=slurm
SlurmctldPort=6817
SlurmdPort=6818
AuthType=auth/munge

StateSaveLocation=/var/lib/slurm
SlurmdSpoolDir=/var/lib/slurmd
SwitchType=switch/none
MpiDefault=none
SlurmctldPidFile=/var/run/slurmctld/slurmctld.pid
SlurmdPidFile=/var/run/slurmd/slurmd.pid
ProctrackType=proctrack/cgroup
ReturnToService=0
TaskPlugin=task/cgroup
SlurmdParameters=config_overrides
MailProg=/bin/true

SlurmctldTimeout=300
SlurmdTimeout=300
InactiveLimit=0
MinJobAge=300
KillWait=30
Waittime=0

SchedulerType=sched/backfill
EnforcePartLimits=YES
SelectType=select/cons_tres
SelectTypeParameters=CR_CPU_Memory

SlurmctldDebug=info
SlurmctldLogFile=/var/log/slurm/slurmctld.log
SlurmdDebug=info
SlurmdLogFile=/var/log/slurm/slurmd-%n.log
JobCompType=jobcomp/filetxt
JobCompLoc=/var/log/slurm/jobcomp.log

JobAcctGatherType=jobacct_gather/linux
JobAcctGatherFrequency=5
AccountingStorageType=accounting_storage/slurmdbd
AccountingStorageHost=slurmdbd
AccountingStoragePort=6819
AccountingStorageEnforce=associations

# The maximum array index is MaxArraySize - 1.
MaxArraySize=2001

GresTypes=gpu

NodeName=scc-c[0001-0002] CPUs=128 RealMemory=256000 State=UNKNOWN
NodeName=scc-c[0003-0400] CPUs=128 RealMemory=256000 State=CLOUD
NodeName=scc-g001 CPUs=64 RealMemory=512000 State=UNKNOWN Gres=gpu:4
NodeName=scc-g[002-040] CPUs=64 RealMemory=512000 State=CLOUD Gres=gpu:4

PartitionName=standard Default=YES Nodes=scc-c[0001-0400] MaxNodes=32 MaxTime=1-00:00:00 DefaultTime=00:30:00 State=UP
PartitionName=extended Default=NO Nodes=scc-c[0001-0400] MaxNodes=4 MaxTime=3-00:00:00 DefaultTime=00:30:00 State=UP
PartitionName=accel Default=NO Nodes=scc-g[001-040] MaxNodes=8 MaxTime=20:00:00 DefaultTime=00:30:00 State=UP
PartitionName=debug Default=NO Nodes=scc-c[0001-0400] MaxNodes=2 MaxTime=00:30:00 DefaultTime=00:30:00 State=UP
